# Generated by Django 3.1.4 on 2021-03-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210116_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hastags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtagname', models.CharField(max_length=200)),
                ('hashtagcount', models.IntegerField()),
                ('question', models.ManyToManyField(to='posts.Question')),
            ],
        ),
    ]
