# Generated by Django 3.1.4 on 2021-03-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_hastags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hastags',
            new_name='Hashtag',
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='question',
            field=models.ManyToManyField(to='posts.Question'),
        ),
    ]
