# Generated by Django 3.1.4 on 2021-01-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210116_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='sender',
            new_name='senderr',
        ),
    ]
