# Generated by Django 3.1.4 on 2021-02-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20210118_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Upvote'), (2, 'Downvote'), (3, 'Answered')]),
        ),
    ]
